"""Embedding cache implementation."""

import hashlib
import logging
from datetime import datetime

from app.services.cache.base import BaseCache
from app.services.cache.redis_client import RedisClient
from app.services.cache.types import CachedEmbedding, CacheStats

logger = logging.getLogger(__name__)

# 24 hours in seconds
DEFAULT_TTL = 86400


class EmbeddingCache(BaseCache):
    """Cache for embedding vectors.

    Uses Redis to cache embeddings by text hash.
    This reduces API calls and improves latency for
    repeated embedding requests.

    Key format: embedding:{model}:{text_hash}
    TTL: 24 hours (configurable)
    """

    def __init__(
        self,
        redis_client: RedisClient,
        prefix: str = "embedding",
        default_ttl: int = DEFAULT_TTL,
    ):
        """Initialize embedding cache.

        Args:
            redis_client: Redis client instance.
            prefix: Key prefix for cache entries.
            default_ttl: Default TTL in seconds (24h default).
        """
        self.redis = redis_client
        self.prefix = prefix
        self.default_ttl = default_ttl
        self._hits = 0
        self._misses = 0

    def _make_key(self, text: str, model: str) -> str:
        """Generate cache key from text and model.

        Uses SHA-256 hash of text for consistent key length.

        Args:
            text: Text that was embedded.
            model: Model used for embedding.

        Returns:
            Cache key string.
        """
        text_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
        return f"{self.prefix}:{model}:{text_hash}"

    async def get(self, key: str) -> CachedEmbedding | None:
        """Retrieve cached embedding by key.

        Args:
            key: Cache key (generated by _make_key).

        Returns:
            CachedEmbedding or None if not found.
        """
        data = await self.redis.get_json(key)
        if data is None:
            self._misses += 1
            return None

        self._hits += 1
        return CachedEmbedding.from_dict(data)

    async def get_embedding(
        self,
        text: str,
        model: str,
    ) -> CachedEmbedding | None:
        """Retrieve cached embedding by text and model.

        Convenience method that generates the key automatically.

        Args:
            text: Original text.
            model: Embedding model name.

        Returns:
            CachedEmbedding or None if not found.
        """
        key = self._make_key(text, model)
        return await self.get(key)

    async def set(
        self,
        key: str,
        value: CachedEmbedding,
        ttl: int | None = None,
    ) -> bool:
        """Store embedding in cache.

        Args:
            key: Cache key.
            value: CachedEmbedding to store.
            ttl: TTL in seconds. Uses default_ttl if None.

        Returns:
            True if stored successfully.
        """
        expiry = ttl if ttl is not None else self.default_ttl
        return await self.redis.set_json(key, value.to_dict(), ex=expiry)

    async def set_embedding(
        self,
        text: str,
        embedding: list[float],
        model: str,
        ttl: int | None = None,
    ) -> bool:
        """Store embedding for text.

        Convenience method that generates key and creates CachedEmbedding.

        Args:
            text: Original text.
            embedding: Embedding vector.
            model: Embedding model name.
            ttl: TTL in seconds.

        Returns:
            True if stored successfully.
        """
        key = self._make_key(text, model)
        cached = CachedEmbedding(
            embedding=embedding,
            model=model,
            cached_at=datetime.utcnow(),
        )
        return await self.set(key, cached, ttl)

    async def get_batch(
        self,
        texts: list[str],
        model: str,
    ) -> tuple[list[CachedEmbedding | None], list[int]]:
        """Get cached embeddings for multiple texts.

        Returns both cached results and indices of texts
        that need to be embedded.

        Args:
            texts: List of texts to check.
            model: Embedding model name.

        Returns:
            Tuple of:
                - List of CachedEmbedding or None for each text
                - List of indices that were cache misses
        """
        results: list[CachedEmbedding | None] = []
        misses: list[int] = []

        for i, text in enumerate(texts):
            cached = await self.get_embedding(text, model)
            results.append(cached)
            if cached is None:
                misses.append(i)

        return results, misses

    async def set_batch(
        self,
        texts: list[str],
        embeddings: list[list[float]],
        model: str,
        ttl: int | None = None,
    ) -> int:
        """Store multiple embeddings.

        Args:
            texts: List of original texts.
            embeddings: Corresponding embedding vectors.
            model: Embedding model name.
            ttl: TTL in seconds.

        Returns:
            Number of embeddings stored.
        """
        stored = 0
        for text, embedding in zip(texts, embeddings, strict=True):
            if await self.set_embedding(text, embedding, model, ttl):
                stored += 1
        return stored

    async def delete(self, key: str) -> bool:
        """Delete cached embedding.

        Args:
            key: Cache key.

        Returns:
            True if deleted.
        """
        result = await self.redis.delete(key)
        return result > 0

    async def exists(self, key: str) -> bool:
        """Check if embedding is cached.

        Args:
            key: Cache key.

        Returns:
            True if cached.
        """
        return await self.redis.exists(key)

    async def clear(self, pattern: str | None = None) -> int:
        """Clear embedding cache.

        Args:
            pattern: Optional pattern. Defaults to all embeddings.

        Returns:
            Number of keys deleted.
        """
        search_pattern = pattern or f"{self.prefix}:*"
        keys = await self.redis.scan_keys(search_pattern)
        if not keys:
            return 0
        return await self.redis.delete(*keys)

    async def get_stats(self) -> CacheStats:
        """Get cache statistics.

        Returns:
            CacheStats with hits, misses, and size.
        """
        keys = await self.redis.scan_keys(f"{self.prefix}:*")
        return CacheStats(
            hits=self._hits,
            misses=self._misses,
            size=len(keys),
        )

    def reset_stats(self) -> None:
        """Reset hit/miss counters."""
        self._hits = 0
        self._misses = 0
